### ISSUE TITLE
Facebook share button / Google +1

### ISSUE THREAD

**Issue by deek87** [concrete5cojp/addon_social_share_lite#12]
I noticed that the social share had Facebook's share button and Google's plus one button. I was wondering should we update the script so user's can have the share button on google rather than the plus one button?
https://developers.google.com/+/web/share/

Or should we give users the option to select if they would like the +1/Like buttons or the Facebook Share/Google+ Share buttons

**Comment by hissy** [comment]
We can change the action to "share" from "+1"
